//Generated by FigmaQML

import QtGraphicalEffects 1.14
import QtQuick 2.14
import QtQuick.Shapes 1.14
Rectangle {
    id: figma_28_391
    objectName:"32icon-grid"
    x:0
    y:0
    width:32
    height:32
    color:"#00ffffff"
    clip: true 
    Component.onCompleted: {
    }
}
