//Generated by FigmaQML

import QtGraphicalEffects 1.14
import QtQuick 2.14
import QtQuick.Shapes 1.14
Rectangle {
    id: figma_28_442
    objectName:"Color=On"
    x:0
    y:0
    width:32
    height:32
    color: "transparent"
    clip: true 
    Component.onCompleted: {
    }
}
