//Generated by FigmaQML

import QtGraphicalEffects 1.14
import QtQuick 2.14
import QtQuick.Shapes 1.14
Rectangle {
    id: figma_5_3
    objectName:"Slide 16:9 - 1"
    x:-2298
    y:-2237
    width:1920
    height:1080
    color: "transparent"
    clip: true 
    Item {
        id: figma_5_4
        objectName:"${img}wallpaperbetter 3"
        x:0
        y:0
        width:1920
        height:1200
        OpacityMask {
            anchors.fill:parent
            source: source_figma_5_4
            maskSource: maskSource_figma_5_4
        }
        Image {
            id: source_figma_5_4
            layer.enabled: true
            fillMode: Image.PreserveAspectCrop
            visible: false
            mipmap: true
            anchors.fill:parent
            source: "images/c3cd9f34d8a57d95064f8aa054b514732a3948be.jpg"
        }
        Shape {
            id: maskSource_figma_5_4
            anchors.fill: parent
            layer.enabled: true
            visible: false
            ShapePath {
                strokeColor: "transparent"
                strokeWidth:1.01204
                fillColor:"black"
                fillRule: ShapePath.WindingFill
                PathSvg {
                    path: "M0 0L1920 0L1920 1200L0 1200L0 0Z"
                } 
            }
        }
        Shape {
            anchors.fill: parent
            ShapePath {
                strokeColor: "transparent"
                strokeWidth:1.01204
                fillColor:"#00000000"
                id: svgpath_figma_5_4
                fillRule: ShapePath.WindingFill
                PathSvg {
                    path: "M0 0L1920 0L1920 1200L0 1200L0 0Z"
                } 
            }
        }
    } 
    Item {
        id: figma_5_5
        objectName:"${img}Trusted technology 1"
        x:681
        y:121
        width:548.524
        height:165.974
        OpacityMask {
            anchors.fill:parent
            source: source_figma_5_5
            maskSource: maskSource_figma_5_5
        }
        Image {
            id: source_figma_5_5
            layer.enabled: true
            fillMode: Image.PreserveAspectCrop
            visible: false
            mipmap: true
            anchors.fill:parent
            source: "images/bb9f802870f08ace1b8dd08cf690158a166c484c.png"
        }
        Shape {
            id: maskSource_figma_5_5
            anchors.fill: parent
            layer.enabled: true
            visible: false
            ShapePath {
                strokeColor: "transparent"
                strokeWidth:1.01204
                fillColor:"black"
                fillRule: ShapePath.WindingFill
                PathSvg {
                    path: "M0 0L548.524 0L548.524 165.974L0 165.974L0 0Z"
                } 
            }
        }
        Shape {
            anchors.fill: parent
            ShapePath {
                strokeColor: "transparent"
                strokeWidth:1.01204
                fillColor:"#00000000"
                id: svgpath_figma_5_5
                fillRule: ShapePath.WindingFill
                PathSvg {
                    path: "M0 0L548.524 0L548.524 165.974L0 165.974L0 0Z"
                } 
            }
        }
    } 
    Item {
        id: figma_5_6
        objectName:"${img}logo 1"
        x:54
        y:41
        width:204.431
        height:79.9509
        OpacityMask {
            anchors.fill:parent
            source: source_figma_5_6
            maskSource: maskSource_figma_5_6
        }
        Image {
            id: source_figma_5_6
            layer.enabled: true
            fillMode: Image.PreserveAspectCrop
            visible: false
            mipmap: true
            anchors.fill:parent
            source: "images/e99ad3fe256c5ef6a2bef27acf357cad2756b080.png"
        }
        Shape {
            id: maskSource_figma_5_6
            anchors.fill: parent
            layer.enabled: true
            visible: false
            ShapePath {
                strokeColor: "transparent"
                strokeWidth:1.01204
                fillColor:"black"
                fillRule: ShapePath.WindingFill
                PathSvg {
                    path: "M0 0L204.431 0L204.431 79.9509L0 79.9509L0 0Z"
                } 
            }
        }
        Shape {
            anchors.fill: parent
            ShapePath {
                strokeColor: "transparent"
                strokeWidth:1.01204
                fillColor:"#00000000"
                id: svgpath_figma_5_6
                fillRule: ShapePath.WindingFill
                PathSvg {
                    path: "M0 0L204.431 0L204.431 79.9509L0 79.9509L0 0Z"
                } 
            }
        }
    } 
    Rectangle {
        id: figma_5_7
        objectName:"Frame 1"
        x:877
        y:834
        width:156.866
        height:149.781
        color: "transparent"
        clip: true 
        Item {
            id: figma_5_8
            objectName:"fingerprint 1"
            x:1
            y:1
            width:155.854
            height:148.769
            OpacityMask {
                anchors.fill:parent
                source: source_figma_5_8
                maskSource: maskSource_figma_5_8
            }
            Image {
                id: source_figma_5_8
                layer.enabled: true
                fillMode: Image.PreserveAspectCrop
                visible: false
                mipmap: true
                anchors.fill:parent
                source: "images/dd496e382fa88f6e7bb8538915db9fd5c1570c65.png"
            }
            Shape {
                id: maskSource_figma_5_8
                anchors.fill: parent
                layer.enabled: true
                visible: false
                ShapePath {
                    strokeColor: "transparent"
                    strokeWidth:1.01204
                    fillColor:"black"
                    fillRule: ShapePath.WindingFill
                    PathSvg {
                        path: "M0 0L155.854 0L155.854 148.769L0 148.769L0 0Z"
                    } 
                }
            }
            Shape {
                anchors.fill: parent
                ShapePath {
                    strokeColor: "transparent"
                    strokeWidth:1.01204
                    fillColor:"#00000000"
                    id: svgpath_figma_5_8
                    fillRule: ShapePath.WindingFill
                    PathSvg {
                        path: "M0 0L155.854 0L155.854 148.769L0 148.769L0 0Z"
                    } 
                }
            }
        } 
    }
    Color_On_figma {
        id: figma_28_471
        objectName:"32/Cloudy"
        x:1606
        y:24
        width:73
        height:73
        C32icon_grid_figma {
            id: figma_i28_471_9_1012
            objectName:"32icon-grid"
            visible: false
            width:73
            height:73
            Rectangle {
                id: figma_i28_471_9_1012_5_1285
                objectName:"Group 156"
                opacity: 0.9
                x:0
                y:0
                width:73
                height:73
                color: "transparent"
                clip: false 
                Shape {
                    id: figma_i28_471_9_1012_5_1286
                    objectName:"Rectangle 908"
                    x:13
                    y:4
                    width:45.625
                    height:63.875
                    ShapePath {
                        joinStyle: ShapePath.MiterJoin
                        strokeColor: "#54f8ccd5"
                        strokeWidth:0.1
                        fillColor:"#ffc4c4c4"
                        id: svgpath_figma_i28_471_9_1012_5_1286
                        fillRule: ShapePath.WindingFill
                        PathSvg {
                            path: "M0 0L0 -0.05L-0.05 -0.05L-0.05 0L0 0ZM45.625 0L45.675 0L45.675 -0.05L45.625 -0.05L45.625 0ZM45.625 63.875L45.625 63.925L45.675 63.925L45.675 63.875L45.625 63.875ZM0 63.875L-0.05 63.875L-0.05 63.925L0 63.925L0 63.875ZM0 0.05L45.625 0.05L45.625 -0.05L0 -0.05L0 0.05ZM45.575 0L45.575 63.875L45.675 63.875L45.675 0L45.575 0ZM45.625 63.825L0 63.825L0 63.925L45.625 63.925L45.625 63.825ZM0.05 63.875L0.05 0L-0.05 0L-0.05 63.875L0.05 63.875Z"
                        } 
                    }
                }
                Shape {
                    id: figma_i28_471_9_1012_5_1316
                    objectName:"Rectangle 911"
                    x:18
                    y:18
                    width:36.5
                    height:36.5
                    ShapePath {
                        joinStyle: ShapePath.MiterJoin
                        strokeColor: "#54f8ccd5"
                        strokeWidth:0.1
                        fillColor:"#ffc4c4c4"
                        id: svgpath_figma_i28_471_9_1012_5_1316
                        fillRule: ShapePath.WindingFill
                        PathSvg {
                            path: "M0 0L0 -0.05L-0.05 -0.05L-0.05 0L0 0ZM36.5 0L36.55 0L36.55 -0.05L36.5 -0.05L36.5 0ZM36.5 36.5L36.5 36.55L36.55 36.55L36.55 36.5L36.5 36.5ZM0 36.5L-0.05 36.5L-0.05 36.55L0 36.55L0 36.5ZM0 0.05L36.5 0.05L36.5 -0.05L0 -0.05L0 0.05ZM36.45 0L36.45 36.5L36.55 36.5L36.55 0L36.45 0ZM36.5 36.45L0 36.45L0 36.55L36.5 36.55L36.5 36.45ZM0.05 36.5L0.05 0L-0.05 0L-0.05 36.5L0.05 36.5Z"
                        } 
                    }
                }
                Shape {
                    id: figma_i28_471_9_1012_5_1287
                    objectName:"Rectangle 909"
                    x:4
                    y:13
                    width:63.875
                    height:45.625
                    ShapePath {
                        joinStyle: ShapePath.MiterJoin
                        strokeColor: "#54f8ccd5"
                        strokeWidth:0.1
                        fillColor:"#ffc4c4c4"
                        id: svgpath_figma_i28_471_9_1012_5_1287
                        fillRule: ShapePath.WindingFill
                        PathSvg {
                            path: "M63.875 2.49292e-06L63.925 2.49292e-06L63.925 -0.0499975L63.875 -0.0499975L63.875 2.49292e-06ZM63.875 45.625L63.875 45.675L63.925 45.675L63.925 45.625L63.875 45.625ZM0 45.625L-0.05 45.625L-0.05 45.675L0 45.675L0 45.625ZM2.23365e-06 0L2.2356e-06 -0.05L-0.0499978 -0.05L-0.0499978 -2.44784e-09L2.23365e-06 0ZM63.825 2.49292e-06L63.825 45.625L63.925 45.625L63.925 2.49292e-06L63.825 2.49292e-06ZM63.875 45.575L0 45.575L0 45.675L63.875 45.675L63.875 45.575ZM0.05 45.625L0.0500022 2.44784e-09L-0.0499978 -2.44784e-09L-0.05 45.625L0.05 45.625ZM2.2317e-06 0.05L63.875 0.0500025L63.875 -0.0499975L2.2356e-06 -0.05L2.2317e-06 0.05Z"
                        } 
                    }
                }
                Shape {
                    id: figma_i28_471_9_1012_5_1288
                    objectName:"Rectangle 910"
                    x:9
                    y:9
                    width:54.75
                    height:54.75
                    ShapePath {
                        joinStyle: ShapePath.MiterJoin
                        strokeColor: "#54f8ccd5"
                        strokeWidth:0.1
                        fillColor:"#ffc4c4c4"
                        id: svgpath_figma_i28_471_9_1012_5_1288
                        fillRule: ShapePath.WindingFill
                        PathSvg {
                            path: "M54.75 2.9915e-06L54.8 2.9915e-06L54.8 -0.049997L54.75 -0.049997L54.75 2.9915e-06ZM54.75 54.75L54.75 54.8L54.8 54.8L54.8 54.75L54.75 54.75ZM0 54.75L-0.05 54.75L-0.05 54.8L0 54.8L0 54.75ZM1.91456e-06 0L1.91729e-06 -0.05L-0.0499981 -0.05L-0.0499981 -1.74846e-09L1.91456e-06 0ZM54.7 2.9915e-06L54.7 54.75L54.8 54.75L54.8 2.9915e-06L54.7 2.9915e-06ZM54.75 54.7L0 54.7L0 54.8L54.75 54.8L54.75 54.7ZM0.05 54.75L0.0500019 1.74846e-09L-0.0499981 -1.74846e-09L-0.05 54.75L0.05 54.75ZM1.91183e-06 0.05L54.75 0.050003L54.75 -0.049997L1.91729e-06 -0.05L1.91183e-06 0.05Z"
                        } 
                    }
                }
                Shape {
                    id: figma_i28_471_9_1012_5_1289
                    objectName:"Ellipse 48"
                    x:4
                    y:4
                    width:63.875
                    height:63.875
                    ShapePath {
                        joinStyle: ShapePath.MiterJoin
                        strokeColor: "#54f8ccd5"
                        strokeWidth:0.1
                        fillColor:"#ffc4c4c4"
                        id: svgpath_figma_i28_471_9_1012_5_1289
                        fillRule: ShapePath.WindingFill
                        PathSvg {
                            path: "M63.825 31.9375C63.825 49.5485 49.5485 63.825 31.9375 63.825L31.9375 63.925C49.6037 63.925 63.925 49.6037 63.925 31.9375L63.825 31.9375ZM31.9375 63.825C14.3265 63.825 0.05 49.5485 0.05 31.9375L-0.05 31.9375C-0.05 49.6037 14.2713 63.925 31.9375 63.925L31.9375 63.825ZM0.05 31.9375C0.05 14.3265 14.3265 0.05 31.9375 0.05L31.9375 -0.05C14.2713 -0.05 -0.05 14.2713 -0.05 31.9375L0.05 31.9375ZM31.9375 0.05C49.5485 0.05 63.825 14.3265 63.825 31.9375L63.925 31.9375C63.925 14.2713 49.6037 -0.05 31.9375 -0.05L31.9375 0.05Z"
                        } 
                    }
                }
                Shape {
                    id: figma_i28_471_9_1012_5_1290
                    objectName:"Ellipse 46"
                    x:18
                    y:18
                    width:36.5
                    height:36.5
                    ShapePath {
                        joinStyle: ShapePath.MiterJoin
                        strokeColor: "#54f8ccd5"
                        strokeWidth:0.1
                        fillColor:"#ffc4c4c4"
                        id: svgpath_figma_i28_471_9_1012_5_1290
                        fillRule: ShapePath.WindingFill
                        PathSvg {
                            path: "M36.45 18.25C36.45 28.3016 28.3016 36.45 18.25 36.45L18.25 36.55C28.3568 36.55 36.55 28.3568 36.55 18.25L36.45 18.25ZM18.25 36.45C8.19842 36.45 0.05 28.3016 0.05 18.25L-0.05 18.25C-0.05 28.3568 8.14319 36.55 18.25 36.55L18.25 36.45ZM0.05 18.25C0.05 8.19842 8.19842 0.05 18.25 0.05L18.25 -0.05C8.14319 -0.05 -0.05 8.14319 -0.05 18.25L0.05 18.25ZM18.25 0.05C28.3016 0.05 36.45 8.19842 36.45 18.25L36.55 18.25C36.55 8.14319 28.3568 -0.05 18.25 -0.05L18.25 0.05Z"
                        } 
                    }
                }
                Shape {
                    id: figma_i28_471_9_1012_5_1291
                    objectName:"Vector 25"
                    x:0
                    y:0
                    width:73
                    height:73
                    ShapePath {
                        joinStyle: ShapePath.MiterJoin
                        strokeColor: "#54f8ccd5"
                        strokeWidth:0.1
                        fillColor:"transparent"
                        id: svgpath_figma_i28_471_9_1012_5_1291
                        fillRule: ShapePath.WindingFill
                        PathSvg {
                            path: "M-0.0353553 0.0353553L72.9646 73.0354L73.0354 72.9646L0.0353553 -0.0353553L-0.0353553 0.0353553Z"
                        } 
                    }
                }
                Shape {
                    id: figma_i28_471_9_1012_5_1292
                    objectName:"Vector 27"
                    transform: Matrix4x4 {
                        matrix: Qt.matrix4x4(
                        1, 9.09098e-08, 36.5, 0,
                        -5.84079e-07, 1, 0, 0,
                        0, 0, 1, 0,
                        0, 0, 0, 1)
                    }
                    x:36
                    y:0
                    width:0
                    height:73
                    ShapePath {
                        joinStyle: ShapePath.MiterJoin
                        strokeColor: "#54f8ccd5"
                        strokeWidth:0.1
                        fillColor:"transparent"
                        id: svgpath_figma_i28_471_9_1012_5_1292
                        fillRule: ShapePath.WindingFill
                        PathSvg {
                            path: "M-0.05 0L-0.05 73L0.05 73L0.05 0L-0.05 0Z"
                        } 
                    }
                }
                Shape {
                    id: figma_i28_471_9_1012_5_1293
                    objectName:"Vector 29"
                    transform: Matrix4x4 {
                        matrix: Qt.matrix4x4(
                        1, 9.09098e-08, 25.0938, 0,
                        -5.84079e-07, 1, 0, 0,
                        0, 0, 1, 0,
                        0, 0, 0, 1)
                    }
                    x:25
                    y:0
                    width:0
                    height:73
                    ShapePath {
                        joinStyle: ShapePath.MiterJoin
                        strokeColor: "#54f8ccd5"
                        strokeWidth:0.1
                        fillColor:"transparent"
                        id: svgpath_figma_i28_471_9_1012_5_1293
                        fillRule: ShapePath.WindingFill
                        PathSvg {
                            path: "M-0.05 0L-0.05 73L0.05 73L0.05 0L-0.05 0Z"
                        } 
                    }
                }
                Shape {
                    id: figma_i28_471_9_1012_5_1294
                    objectName:"Vector 32"
                    transform: Matrix4x4 {
                        matrix: Qt.matrix4x4(
                        4.73283e-07, -1, 73, 0,
                        1, 7.36648e-08, 25.0938, 0,
                        0, 0, 1, 0,
                        0, 0, 0, 1)
                    }
                    x:73
                    y:25
                    width:0
                    height:73
                    ShapePath {
                        joinStyle: ShapePath.MiterJoin
                        strokeColor: "#54f8ccd5"
                        strokeWidth:0.1
                        fillColor:"transparent"
                        id: svgpath_figma_i28_471_9_1012_5_1294
                        fillRule: ShapePath.WindingFill
                        PathSvg {
                            path: "M-0.05 0L-0.05 73L0.05 73L0.05 0L-0.05 0Z"
                        } 
                    }
                }
                Shape {
                    id: figma_i28_471_9_1012_5_1295
                    objectName:"Vector 30"
                    transform: Matrix4x4 {
                        matrix: Qt.matrix4x4(
                        1, 9.09098e-08, 47.9063, 0,
                        -5.84079e-07, 1, 0, 0,
                        0, 0, 1, 0,
                        0, 0, 0, 1)
                    }
                    x:47
                    y:0
                    width:0
                    height:73
                    ShapePath {
                        joinStyle: ShapePath.MiterJoin
                        strokeColor: "#54f8ccd5"
                        strokeWidth:0.1
                        fillColor:"transparent"
                        id: svgpath_figma_i28_471_9_1012_5_1295
                        fillRule: ShapePath.WindingFill
                        PathSvg {
                            path: "M-0.05 0L-0.05 73L0.05 73L0.05 0L-0.05 0Z"
                        } 
                    }
                }
                Shape {
                    id: figma_i28_471_9_1012_5_1296
                    objectName:"Vector 33"
                    transform: Matrix4x4 {
                        matrix: Qt.matrix4x4(
                        4.73283e-07, -1, 73, 0,
                        1, 7.36648e-08, 47.9063, 0,
                        0, 0, 1, 0,
                        0, 0, 0, 1)
                    }
                    x:73
                    y:47
                    width:0
                    height:73
                    ShapePath {
                        joinStyle: ShapePath.MiterJoin
                        strokeColor: "#54f8ccd5"
                        strokeWidth:0.1
                        fillColor:"transparent"
                        id: svgpath_figma_i28_471_9_1012_5_1296
                        fillRule: ShapePath.WindingFill
                        PathSvg {
                            path: "M-0.05 0L-0.05 73L0.05 73L0.05 0L-0.05 0Z"
                        } 
                    }
                }
                Shape {
                    id: figma_i28_471_9_1012_5_1297
                    objectName:"Vector 28"
                    transform: Matrix4x4 {
                        matrix: Qt.matrix4x4(
                        -1.10796e-07, -1, 73, 0,
                        1, -1.7245e-08, 36.5, 0,
                        0, 0, 1, 0,
                        0, 0, 0, 1)
                    }
                    x:73
                    y:36
                    width:0
                    height:73
                    ShapePath {
                        joinStyle: ShapePath.MiterJoin
                        strokeColor: "#54f8ccd5"
                        strokeWidth:0.1
                        fillColor:"transparent"
                        id: svgpath_figma_i28_471_9_1012_5_1297
                        fillRule: ShapePath.WindingFill
                        PathSvg {
                            path: "M-0.05 0L-0.05 73L0.05 73L0.05 0L-0.05 0Z"
                        } 
                    }
                }
                Shape {
                    id: figma_i28_471_9_1012_5_1298
                    objectName:"Vector 26"
                    transform: Matrix4x4 {
                        matrix: Qt.matrix4x4(
                        -1, 0, 73, 0,
                        0, 1, 0, 0,
                        0, 0, 1, 0,
                        0, 0, 0, 1)
                    }
                    x:73
                    y:0
                    width:73
                    height:73
                    ShapePath {
                        joinStyle: ShapePath.MiterJoin
                        strokeColor: "#54f8ccd5"
                        strokeWidth:0.1
                        fillColor:"transparent"
                        id: svgpath_figma_i28_471_9_1012_5_1298
                        fillRule: ShapePath.WindingFill
                        PathSvg {
                            path: "M-0.0353553 0.0353553L72.9646 73.0354L73.0354 72.9646L0.0353553 -0.0353553L-0.0353553 0.0353553Z"
                        } 
                    }
                }
            }
        }
        Shape {
            id: figma_i28_471_9_1013
            objectName:"for edit"
            visible: false
            x:4
            y:4
            width:63.875
            height:63.875
            ShapePath {
                strokeColor: "transparent"
                strokeWidth:0
                fillColor:"#00000000"
                id: svgpath_figma_i28_471_9_1013
                PathSvg {
                    path: "M18.9728 14.2744C20.6562 13.8901 22.4054 13.6875 24.2002 13.6875C35.2885 13.6875 44.6351 21.4204 47.498 31.9691C47.821 31.9482 48.1468 31.9375 48.475 31.9375C50.985 31.9375 53.3548 32.5602 55.4485 33.6647C59.2259 32.06 61.8749 28.3159 61.8749 23.9531C61.8749 18.1766 57.231 13.4847 51.4728 13.4072C51.5125 13.5663 51.5499 13.7263 51.5852 13.887C50.9196 14.0201 50.2773 14.2176 49.6649 14.4727C49.6016 14.1695 49.5295 13.8696 49.449 13.5732C48.5802 13.7294 47.7483 13.992 46.9674 14.3471C46.8186 13.6849 46.6175 13.0425 46.3686 12.4245C47.1402 12.0922 47.9517 11.835 48.7941 11.6623C46.4284 5.98827 40.8287 2 34.2975 2C26.8033 2 20.5355 7.25099 18.9728 14.2744ZM57.4342 34.9165C61.2765 32.7719 63.8749 28.666 63.8749 23.9531C63.8749 17.0237 58.2575 11.4062 51.328 11.4062C51.1676 11.4062 51.0078 11.4093 50.8488 11.4152C48.3139 4.74235 41.8595 0 34.2975 0C25.4836 0 18.1745 6.44239 16.8222 14.875C7.06488 18.1102 0 27.5902 0 38.7812C0 52.6401 10.8348 63.875 24.2002 63.875C26.8753 63.875 29.4491 63.4249 31.8549 62.5938L42.421 62.5938C44.2793 63.4184 46.3257 63.8749 48.475 63.8749C56.9802 63.8749 63.875 56.7255 63.875 47.9062C63.875 42.5523 61.334 37.8137 57.4342 34.9165ZM39.1223 60.5938L36.1729 60.5938C36.7553 60.2493 37.3225 59.8805 37.8734 59.4887C38.2702 59.8793 38.6871 60.2483 39.1223 60.5938ZM47.9062 60.5938L47.9062 61.8625C48.0949 61.8707 48.2845 61.8749 48.475 61.8749C55.8079 61.8749 61.875 55.6899 61.875 47.9062C61.875 40.1225 55.8079 33.9375 48.475 33.9375C46.7253 33.9375 45.0477 34.2896 43.5075 34.9316C43.3843 34.2617 43.2296 33.6034 43.045 32.9585C43.8338 32.6502 44.6534 32.4072 45.4977 32.2357C42.778 22.6348 34.2284 15.6875 24.2002 15.6875C12.0071 15.6875 2 25.958 2 38.7812C2 51.6045 12.0071 61.875 24.2002 61.875C24.3212 61.875 24.4419 61.874 24.5625 61.872L24.5625 60.5938L31.5035 60.5938C32.4916 60.2355 33.4486 59.8065 34.3685 59.3125L40.7412 59.3125C41.4082 59.8043 42.1196 60.2339 42.8675 60.5938L47.9062 60.5938Z"
                } 
            }
        }
        Item {
            id: figma_i28_471_9_1039
            objectName:"outline"
            x: 4.5625
            y: 4.5625
            width:63.875
            height:63.875
            Image {
                id: i_figma_i28_471_9_1039
                anchors.centerIn: parent
                mipmap: true
                fillMode: Image.PreserveAspectFit
                source: "images/I28_471_9_1039.png"
            }
        }
    }
    Text {
        id: figma_28_530
        objectName:"34° C"
        x:1699
        y:24
        width:84
        height:43
        color:"#ffffffff"
        wrapMode: TextEdit.WordWrap
        text:"34° C"
        font.family: "MS Shell Dlg 2"
        font.italic: false
        font.letterSpacing: 0
        font.pixelSize: 32
        font.weight: Font.Normal
        horizontalAlignment: Text.AlignLeft
        verticalAlignment: Text.AlignTop
    }
    Text {
        id: figma_28_531
        objectName:"Ho Chi Minh city"
        x:1699
        y:65
        width:201
        height:32
        color:"#ffffffff"
        wrapMode: TextEdit.WordWrap
        text:"Ho Chi Minh city"
        font.family: "MS Shell Dlg 2"
        font.italic: false
        font.letterSpacing: 0
        font.pixelSize: 24
        font.weight: Font.Normal
        horizontalAlignment: Text.AlignLeft
        verticalAlignment: Text.AlignTop
    }
    Text {
        id: figma_28_536
        objectName:"Friday, July 22nd"
        x:794
        y:610
        width:332
        height:53
        color:"#ffffffff"
        wrapMode: TextEdit.WordWrap
        text:"Friday, July 22nd"
        font.family: "MS Shell Dlg 2"
        font.italic: false
        font.letterSpacing: 0
        font.pixelSize: 40
        font.weight: Font.Normal
        horizontalAlignment: Text.AlignLeft
        verticalAlignment: Text.AlignTop
    }
    Shape {
        id: figma_28_534
        objectName:"Ellipse 14"
        x:734
        y:340
        width:443
        height:443
        ShapePath {
            strokeColor: "transparent"
            strokeWidth:1
            fillColor:"transparent"
            id: svgpath_figma_28_534
        }
    }
    Text {
        id: figma_28_535
        objectName:"18:09:36"
        x:548
        y:465
        width:816
        height:171
        color:"#ffffffff"
        wrapMode: TextEdit.WordWrap
        text:"18:09:36
"
        font.family: "MS Shell Dlg 2"
        font.italic: false
        font.letterSpacing: 0
        font.pixelSize: 96
        font.weight: Font.Normal
        horizontalAlignment: Text.AlignHCenter
        verticalAlignment: Text.AlignTop
    }
}
