//Generated by FigmaQML

import QtGraphicalEffects 1.14
import QtQuick 2.14
import QtQuick.Shapes 1.14
Rectangle {
    id: figma_5_10
    objectName:"Slide 16:9 - 2"
    x:-191
    y:-2220
    width:1920
    height:1080
    color: "transparent"
    clip: true 
    Item {
        id: figma_5_11
        objectName:"wallpaperbetter 3"
        x:0
        y:0
        width:1920
        height:1200
        OpacityMask {
            anchors.fill:parent
            source: source_figma_5_11
            maskSource: maskSource_figma_5_11
        }
        Image {
            id: source_figma_5_11
            layer.enabled: true
            fillMode: Image.PreserveAspectCrop
            visible: false
            mipmap: true
            anchors.fill:parent
            source: "images/c3cd9f34d8a57d95064f8aa054b514732a3948be.jpg"
        }
        Shape {
            id: maskSource_figma_5_11
            anchors.fill: parent
            layer.enabled: true
            visible: false
            ShapePath {
                strokeColor: "transparent"
                strokeWidth:1.01204
                fillColor:"black"
                fillRule: ShapePath.WindingFill
                PathSvg {
                    path: "M0 0L1920 0L1920 1200L0 1200L0 0Z"
                } 
            }
        }
        Shape {
            anchors.fill: parent
            ShapePath {
                strokeColor: "transparent"
                strokeWidth:1.01204
                fillColor:"#00000000"
                id: svgpath_figma_5_11
                fillRule: ShapePath.WindingFill
                PathSvg {
                    path: "M0 0L1920 0L1920 1200L0 1200L0 0Z"
                } 
            }
        }
    } 
    Item {
        id: figma_5_12
        objectName:"Trusted technology 1"
        x:681
        y:121
        width:548.52
        height:165.973
        OpacityMask {
            anchors.fill:parent
            source: source_figma_5_12
            maskSource: maskSource_figma_5_12
        }
        Image {
            id: source_figma_5_12
            layer.enabled: true
            fillMode: Image.PreserveAspectCrop
            visible: false
            mipmap: true
            anchors.fill:parent
            source: "images/bb9f802870f08ace1b8dd08cf690158a166c484c.png"
        }
        Shape {
            id: maskSource_figma_5_12
            anchors.fill: parent
            layer.enabled: true
            visible: false
            ShapePath {
                strokeColor: "transparent"
                strokeWidth:1
                fillColor:"black"
                fillRule: ShapePath.WindingFill
                PathSvg {
                    path: "M0 0L548.52 0L548.52 165.973L0 165.973L0 0Z"
                } 
            }
        }
        Shape {
            anchors.fill: parent
            ShapePath {
                strokeColor: "transparent"
                strokeWidth:1
                fillColor:"#00000000"
                id: svgpath_figma_5_12
                fillRule: ShapePath.WindingFill
                PathSvg {
                    path: "M0 0L548.52 0L548.52 165.973L0 165.973L0 0Z"
                } 
            }
        }
    } 
    Item {
        id: figma_5_13
        objectName:"logo 1"
        x:54
        y:41
        width:202
        height:79
        OpacityMask {
            anchors.fill:parent
            source: source_figma_5_13
            maskSource: maskSource_figma_5_13
        }
        Image {
            id: source_figma_5_13
            layer.enabled: true
            fillMode: Image.PreserveAspectCrop
            visible: false
            mipmap: true
            anchors.fill:parent
            source: "images/e99ad3fe256c5ef6a2bef27acf357cad2756b080.png"
        }
        Shape {
            id: maskSource_figma_5_13
            anchors.fill: parent
            layer.enabled: true
            visible: false
            ShapePath {
                strokeColor: "transparent"
                strokeWidth:1
                fillColor:"black"
                fillRule: ShapePath.WindingFill
                PathSvg {
                    path: "M0 0L202 0L202 79L0 79L0 0Z"
                } 
            }
        }
        Shape {
            anchors.fill: parent
            ShapePath {
                strokeColor: "transparent"
                strokeWidth:1
                fillColor:"#00000000"
                id: svgpath_figma_5_13
                fillRule: ShapePath.WindingFill
                PathSvg {
                    path: "M0 0L202 0L202 79L0 79L0 0Z"
                } 
            }
        }
    } 
    Item {
        id: figma_5_14
        objectName:"icone-de-localisation-jaune 1"
        x:1343
        y:530
        width:130.723
        height:115
        OpacityMask {
            anchors.fill:parent
            source: source_figma_5_14
            maskSource: maskSource_figma_5_14
        }
        Image {
            id: source_figma_5_14
            layer.enabled: true
            fillMode: Image.PreserveAspectCrop
            visible: false
            mipmap: true
            anchors.fill:parent
            source: "images/4cab2c4f049245fd04d41deeeeb80b310ae7954f.png"
        }
        Shape {
            id: maskSource_figma_5_14
            anchors.fill: parent
            layer.enabled: true
            visible: false
            ShapePath {
                strokeColor: "transparent"
                strokeWidth:0.449219
                fillColor:"black"
                fillRule: ShapePath.WindingFill
                PathSvg {
                    path: "M0 0L130.723 0L130.723 115L0 115L0 0Z"
                } 
            }
        }
        Shape {
            anchors.fill: parent
            ShapePath {
                strokeColor: "transparent"
                strokeWidth:0.449219
                fillColor:"#00000000"
                id: svgpath_figma_5_14
                fillRule: ShapePath.WindingFill
                PathSvg {
                    path: "M0 0L130.723 0L130.723 115L0 115L0 0Z"
                } 
            }
        }
    } 
    Item {
        id: figma_5_15
        objectName:"icone-de-localisation-jaune 2"
        x:465
        y:432
        width:112
        height:98
        OpacityMask {
            anchors.fill:parent
            source: source_figma_5_15
            maskSource: maskSource_figma_5_15
        }
        Image {
            id: source_figma_5_15
            layer.enabled: true
            fillMode: Image.PreserveAspectCrop
            visible: false
            mipmap: true
            anchors.fill:parent
            source: "images/4cab2c4f049245fd04d41deeeeb80b310ae7954f.png"
        }
        Shape {
            id: maskSource_figma_5_15
            anchors.fill: parent
            layer.enabled: true
            visible: false
            ShapePath {
                strokeColor: "transparent"
                strokeWidth:0.457031
                fillColor:"black"
                fillRule: ShapePath.WindingFill
                PathSvg {
                    path: "M0 0L112 0L112 98L0 98L0 0Z"
                } 
            }
        }
        Shape {
            anchors.fill: parent
            ShapePath {
                strokeColor: "transparent"
                strokeWidth:0.457031
                fillColor:"#00000000"
                id: svgpath_figma_5_15
                fillRule: ShapePath.WindingFill
                PathSvg {
                    path: "M0 0L112 0L112 98L0 98L0 0Z"
                } 
            }
        }
    } 
    Item {
        id: figma_5_16
        objectName:"icone-de-localisation-jaune 3"
        x:1349
        y:627
        width:71.6133
        height:63
        OpacityMask {
            anchors.fill:parent
            source: source_figma_5_16
            maskSource: maskSource_figma_5_16
        }
        Image {
            id: source_figma_5_16
            layer.enabled: true
            fillMode: Image.PreserveAspectCrop
            visible: false
            mipmap: true
            anchors.fill:parent
            source: "images/4cab2c4f049245fd04d41deeeeb80b310ae7954f.png"
        }
        Shape {
            id: maskSource_figma_5_16
            anchors.fill: parent
            layer.enabled: true
            visible: false
            ShapePath {
                strokeColor: "transparent"
                strokeWidth:0.246094
                fillColor:"black"
                fillRule: ShapePath.WindingFill
                PathSvg {
                    path: "M0 0L71.6133 0L71.6133 63L0 63L0 0Z"
                } 
            }
        }
        Shape {
            anchors.fill: parent
            ShapePath {
                strokeColor: "transparent"
                strokeWidth:0.246094
                fillColor:"#00000000"
                id: svgpath_figma_5_16
                fillRule: ShapePath.WindingFill
                PathSvg {
                    path: "M0 0L71.6133 0L71.6133 63L0 63L0 0Z"
                } 
            }
        }
    } 
    Text {
        id: figma_5_17
        objectName:"06:15 PM Friday, July 22nd"
        x:1402
        y:28
        width:446.31
        height:107.28
        color:"#ffffffff"
        wrapMode: TextEdit.WordWrap
        text:"06:15 PM
Friday, July 22nd"
        font.family: "MS Shell Dlg 2"
        font.italic: false
        font.letterSpacing: 0
        font.pixelSize: 24
        font.weight: Font.Normal
        horizontalAlignment: Text.AlignRight
        verticalAlignment: Text.AlignTop
    }
    Item {
        id: figma_5_18
        objectName:"Windows-10-user-icon-big 1"
        x:823
        y:312
        width:256
        height:256
        OpacityMask {
            anchors.fill:parent
            source: source_figma_5_18
            maskSource: maskSource_figma_5_18
        }
        Image {
            id: source_figma_5_18
            layer.enabled: true
            fillMode: Image.PreserveAspectCrop
            visible: false
            mipmap: true
            anchors.fill:parent
            source: "images/51b1c21cccef5fec3c7b217c86a1a279c71928e3.png"
        }
        Shape {
            id: maskSource_figma_5_18
            anchors.fill: parent
            layer.enabled: true
            visible: false
            ShapePath {
                strokeColor: "transparent"
                strokeWidth:1
                fillColor:"black"
                fillRule: ShapePath.WindingFill
                PathSvg {
                    path: "M0 128C0 57.3076 57.3076 0 128 0L128 0C198.692 0 256 57.3076 256 128L256 128C256 198.692 198.692 256 128 256L128 256C57.3076 256 0 198.692 0 128L0 128Z"
                } 
            }
        }
        Shape {
            anchors.fill: parent
            ShapePath {
                strokeColor: "transparent"
                strokeWidth:1
                fillColor:"#00000000"
                id: svgpath_figma_5_18
                fillRule: ShapePath.WindingFill
                PathSvg {
                    path: "M0 128C0 57.3076 57.3076 0 128 0L128 0C198.692 0 256 57.3076 256 128L256 128C256 198.692 198.692 256 128 256L128 256C57.3076 256 0 198.692 0 128L0 128Z"
                } 
            }
        }
    } 
    Shape {
        id: figma_5_19
        objectName:"Rectangle 1"
        x:457
        y:787
        width:211
        height:149
        ShapePath {
            strokeColor: "transparent"
            strokeWidth:1
            fillColor:"#fff3c216"
            id: svgpath_figma_5_19
            fillRule: ShapePath.WindingFill
            PathSvg {
                path: "M0 20C0 8.9543 8.95431 0 20 0L191 0C202.046 0 211 8.9543 211 20L211 129C211 140.046 202.046 149 191 149L20 149C8.9543 149 0 140.046 0 129L0 20Z"
            } 
        }
    }
    Shape {
        id: figma_5_20
        objectName:"Rectangle 3"
        x:1254
        y:790
        width:211
        height:149
        ShapePath {
            strokeColor: "transparent"
            strokeWidth:1
            fillColor:"#fff3c216"
            id: svgpath_figma_5_20
            fillRule: ShapePath.WindingFill
            PathSvg {
                path: "M0 20C0 8.9543 8.95431 0 20 0L191 0C202.046 0 211 8.9543 211 20L211 129C211 140.046 202.046 149 191 149L20 149C8.9543 149 0 140.046 0 129L0 20Z"
            } 
        }
    }
    Text {
        id: figma_5_21
        objectName:"Welcome to BV"
        x:716
        y:599
        width:487
        height:75
        color:"#ffffffff"
        wrapMode: TextEdit.WordWrap
        text:"Welcome to BV"
        font.family: "MS Shell Dlg 2"
        font.italic: false
        font.letterSpacing: 0
        font.pixelSize: 64
        font.weight: Font.Normal
        horizontalAlignment: Text.AlignRight
        verticalAlignment: Text.AlignTop
    }
    Text {
        id: figma_5_22
        objectName:"Employee"
        x:391
        y:949
        width:355
        height:76
        color:"#ffffffff"
        wrapMode: TextEdit.WordWrap
        text:"Employee"
        font.family: "MS Shell Dlg 2"
        font.italic: false
        font.letterSpacing: 0
        font.pixelSize: 64
        font.weight: Font.Normal
        horizontalAlignment: Text.AlignHCenter
        verticalAlignment: Text.AlignTop
    }
    Text {
        id: figma_5_23
        objectName:"Guest"
        x:1203
        y:949
        width:313
        height:85
        color:"#ffffffff"
        wrapMode: TextEdit.WordWrap
        text:"Guest"
        font.family: "MS Shell Dlg 2"
        font.italic: false
        font.letterSpacing: 0
        font.pixelSize: 64
        font.weight: Font.Normal
        horizontalAlignment: Text.AlignHCenter
        verticalAlignment: Text.AlignTop
    }
    Rectangle {
        id: figma_5_24
        objectName:"employee-svgrepo-com 1"
        x:1294
        y:794
        width:131
        height:131
        color: "transparent"
        clip: true 
        Rectangle {
            id: figma_5_25
            objectName:"Group"
            x:13
            y:0
            width:104.11
            height:131
            color: "transparent"
            clip: false 
            Rectangle {
                id: figma_5_26
                objectName:"Group"
                x:0
                y:0
                width:104.11
                height:131
                color: "transparent"
                clip: false 
                Rectangle {
                    id: figma_5_27
                    objectName:"Group"
                    x:0
                    y:0
                    width:104.11
                    height:131
                    color: "transparent"
                    clip: false 
                    Shape {
                        id: figma_5_28
                        objectName:"Vector"
                        x:18
                        y:0
                        width:66.3089
                        height:71.9522
                        ShapePath {
                            strokeColor: "transparent"
                            strokeWidth:1
                            fillColor:"#ff000000"
                            id: svgpath_figma_5_28
                            fillRule: ShapePath.WindingFill
                            PathSvg {
                                path: "M25.1033 71.9522L41.2056 71.9522C55.1732 71.9522 66.3089 60.571 66.3089 46.8489C66.3089 42.3667 66.3089 29.451 66.3089 25.108C66.3089 11.2636 55.0472 0 41.2056 0C21.5838 0 29.2022 0 25.1033 0C11.2612 0 0 11.2636 0 25.108C0 29.6457 0 41.7379 0 46.8489C0 60.5551 11.1121 71.9522 25.1033 71.9522ZM41.2056 7.05414C50.4385 7.05414 59.2547 14.1219 59.2547 26.0298L51.1331 26.0298C39.9805 26.0298 30.6121 17.9509 28.9074 7.05414L41.2056 7.05414ZM7.05414 25.108C7.05414 16.5128 13.1752 9.03588 21.6524 7.38897C20.8285 15.7481 14.9374 22.7548 7.05414 25.1452L7.05414 25.108ZM7.05414 32.4236C15.0672 30.6512 21.7771 25.3874 25.5402 18.361C30.6719 27.2313 40.2565 33.0839 51.1331 33.0839L59.2547 33.0839L59.2547 46.8489C59.2547 56.7388 51.2238 64.898 41.2056 64.898L25.1033 64.898C15.0535 64.898 7.05414 56.7143 7.05414 46.8489L7.05414 32.4236Z"
                            } 
                        }
                    }
                    Shape {
                        id: figma_5_29
                        objectName:"Vector"
                        x:0
                        y:76
                        width:104.11
                        height:54.4131
                        ShapePath {
                            strokeColor: "transparent"
                            strokeWidth:1
                            fillColor:"#ff000000"
                            id: svgpath_figma_5_29
                            fillRule: ShapePath.WindingFill
                            PathSvg {
                                path: "M66.5529 1.79069C66.5515 1.79022 66.5506 1.78975 66.5492 1.78928C66.5478 1.78881 66.5459 1.78834 66.5445 1.78787C57.74 -0.596429 46.3635 -0.595955 37.5605 1.78928C37.559 1.78975 37.5581 1.79022 37.5567 1.79069C15.4434 7.76366 0 27.9512 0 50.8861C0 52.834 1.57919 54.4131 3.52707 54.4131C5.63014 54.4131 98.4795 54.4131 100.583 54.4131C102.53 54.4131 104.11 52.834 104.11 50.8861C104.11 27.9408 88.6663 7.75332 66.5529 1.79069ZM36.2973 42.9417L41.8931 47.359L7.19616 47.359C8.61545 29.773 20.5529 14.609 37.4109 9.18766L42.1565 14.1853L35.0882 39.2148C34.7007 40.587 35.1776 42.0581 36.2973 42.9417ZM52.0548 46.3926L42.5172 38.8644L49.4909 14.1707C49.829 12.9734 49.5111 11.6858 48.6543 10.7833L45.4846 7.44529C49.7561 6.93316 54.3535 6.93269 58.6246 7.44576L55.4554 10.7833C54.5985 11.6858 54.2802 12.9729 54.6188 14.1707L61.5925 38.8644L52.0548 46.3926ZM62.2165 47.3585L67.8119 42.9417C68.9316 42.0581 69.4085 40.587 69.021 39.2148L61.9527 14.1853C65.6143 10.329 64.5289 11.4723 66.6987 9.18672C83.5572 14.6001 95.4951 29.7636 96.913 47.3585L62.2165 47.3585Z"
                            } 
                        }
                    }
                }
            }
        }
    }
    Rectangle {
        id: figma_5_30
        objectName:"programmer-software-engineer-coder-software-developer-svgrepo-com 1"
        x:497
        y:799
        width:131
        height:131
        color: "transparent"
        clip: true 
        Shape {
            id: figma_5_31
            objectName:"Vector"
            x:1
            y:1
            width:128.953
            height:128.861
            ShapePath {
                strokeColor: "transparent"
                strokeWidth:1
                fillColor:"#ff000000"
                id: svgpath_figma_5_31
                fillRule: ShapePath.WindingFill
                PathSvg {
                    path: "M23.2943 88.5192L29.0112 128.861L99.9415 128.861L105.658 88.5192L23.2943 88.5192L23.2943 88.5192ZM64.4764 112.174C61.535 112.174 59.1509 110.562 59.1509 108.575C59.1509 106.588 61.535 104.977 64.4764 104.977C67.4177 104.977 69.8018 106.588 69.8018 108.575C69.8018 110.563 67.4177 112.174 64.4764 112.174ZM118.368 121.541L105.049 121.541L110.316 84.3777L18.6371 84.3777L23.9037 121.541L10.5847 121.541C2.98671 121.541 -2.1315 113.547 0.873308 106.371L19.7092 61.3953C23.3674 52.6594 31.731 47.0001 40.9818 47.0001L48.3946 47.0001L60.1053 64.9197L62.4924 53.2118L58.4964 47.0001L70.5172 47.0001L66.5207 53.2118L68.9027 64.8376L80.5597 47.0001L87.9724 47.0001C97.2233 47.0001 105.587 52.6594 109.245 61.3953L128.08 106.371C131.084 113.546 125.967 121.541 118.368 121.541ZM64.4764 0C75.988 0 85.3202 9.59456 85.3202 21.4298C85.3202 33.2651 75.988 42.8591 64.4764 42.8591C52.9647 42.8591 43.6325 33.2645 43.6325 21.4293C43.6325 9.59404 52.9647 0 64.4764 0Z"
                } 
            }
        }
    }
}
