//Generated by FigmaQML

import QtGraphicalEffects 1.14
import QtQuick 2.14
import QtQuick.Shapes 1.14
Rectangle {
    id: figma_5_147
    objectName:"Slide 4:3 - 1"
    x:2040
    y:-537
    width:1193
    height:495
    color:"#fff3c216"
    clip: true 
    Shape {
        id: figma_5_148
        objectName:"Rectangle 5"
        x:105
        y:248
        width:984
        height:119
        ShapePath {
            strokeColor: "transparent"
            strokeWidth:1
            fillColor:"#ffffffff"
            id: svgpath_figma_5_148
            fillRule: ShapePath.WindingFill
            PathSvg {
                path: "M0 0L984 0L984 119L0 119L0 0Z"
            } 
        }
    }
    Text {
        id: figma_5_149
        objectName:"Please enter your passcode"
        x:256
        y:131
        width:681
        height:67
        color:"#ff000000"
        wrapMode: TextEdit.WordWrap
        text:"Please enter your passcode"
        font.family: "MS Shell Dlg 2"
        font.italic: false
        font.letterSpacing: 0
        font.pixelSize: 50
        font.weight: Font.Normal
        horizontalAlignment: Text.AlignLeft
        verticalAlignment: Text.AlignTop
    }
}
