//Generated by FigmaQML

import QtGraphicalEffects 1.14
import QtQuick 2.14
import QtQuick.Shapes 1.14
Rectangle {
    id: figma_5_130
    objectName:"Slide 16:9 - 3"
    x:-191
    y:-925
    width:1920
    height:1080
    color: "transparent"
    clip: true 
    Shape {
        id: figma_5_131
        objectName:"wallpaperbetter 3"
        x:0
        y:0
        width:1920
        height:1200
        ShapePath {
            strokeColor: "transparent"
            strokeWidth:1.01204
            fillColor:"#ffffffff"
            id: svgpath_figma_5_131
            fillRule: ShapePath.WindingFill
            PathSvg {
                path: "M0 0L1920 0L1920 1200L0 1200L0 0Z"
            } 
        }
    }
    Item {
        id: figma_5_132
        objectName:"BG-8 1"
        x:0
        y:-25
        width:1920
        height:1130
        OpacityMask {
            anchors.fill:parent
            source: source_figma_5_132
            maskSource: maskSource_figma_5_132
        }
        Image {
            id: source_figma_5_132
            layer.enabled: true
            fillMode: Image.PreserveAspectCrop
            visible: false
            mipmap: true
            anchors.fill:parent
            source: "images/c75db96fe239f472297f43674c2bc4f0b17747a5.jpg"
        }
        Shape {
            id: maskSource_figma_5_132
            anchors.fill: parent
            layer.enabled: true
            visible: false
            ShapePath {
                strokeColor: "transparent"
                strokeWidth:1
                fillColor:"black"
                fillRule: ShapePath.WindingFill
                PathSvg {
                    path: "M0 0L1920 0L1920 1130L0 1130L0 0Z"
                } 
            }
        }
        Shape {
            anchors.fill: parent
            ShapePath {
                strokeColor: "transparent"
                strokeWidth:1
                fillColor:"#00000000"
                id: svgpath_figma_5_132
                fillRule: ShapePath.WindingFill
                PathSvg {
                    path: "M0 0L1920 0L1920 1130L0 1130L0 0Z"
                } 
            }
        }
    } 
    Text {
        id: figma_5_133
        objectName:"06:15 PM Friday, July 22nd"
        x:1402
        y:28
        width:446.308
        height:107.276
        color:"#ff000000"
        wrapMode: TextEdit.WordWrap
        text:"06:15 PM
Friday, July 22nd"
        font.family: "MS Shell Dlg 2"
        font.italic: false
        font.letterSpacing: 0
        font.pixelSize: 24
        font.weight: Font.Normal
        horizontalAlignment: Text.AlignRight
        verticalAlignment: Text.AlignTop
    }
    Item {
        id: figma_5_134
        objectName:"MicrosoftTeams-image (3) 1"
        x:23
        y:982
        width:1874
        height:76
        OpacityMask {
            anchors.fill:parent
            source: source_figma_5_134
            maskSource: maskSource_figma_5_134
        }
        Image {
            id: source_figma_5_134
            layer.enabled: true
            fillMode: Image.PreserveAspectCrop
            visible: false
            mipmap: true
            anchors.fill:parent
            source: "images/edf016518fee329caa534e7f7800bf2d6d8caa14.png"
        }
        Shape {
            id: maskSource_figma_5_134
            anchors.fill: parent
            layer.enabled: true
            visible: false
            ShapePath {
                strokeColor: "transparent"
                strokeWidth:1
                fillColor:"black"
                fillRule: ShapePath.WindingFill
                PathSvg {
                    path: "M0 0L1874 0L1874 76L0 76L0 0Z"
                } 
            }
        }
        Shape {
            anchors.fill: parent
            ShapePath {
                strokeColor: "transparent"
                strokeWidth:1
                fillColor:"#00000000"
                id: svgpath_figma_5_134
                fillRule: ShapePath.WindingFill
                PathSvg {
                    path: "M0 0L1874 0L1874 76L0 76L0 0Z"
                } 
            }
        }
    } 
    Text {
        id: figma_5_135
        objectName:"Please scan your QR code into QR Barcode reader"
        x:167
        y:200
        width:1586
        height:85
        color:"#ff000000"
        wrapMode: TextEdit.WordWrap
        text:"Please scan your QR code into QR Barcode reader"
        font.family: "MS Shell Dlg 2"
        font.italic: false
        font.letterSpacing: 0
        font.pixelSize: 64
        font.weight: Font.Normal
        horizontalAlignment: Text.AlignRight
        verticalAlignment: Text.AlignTop
    }
    Item {
        id: figma_5_136
        objectName:"2_36_800 1"
        x:392
        y:350
        width:1136
        height:558
        OpacityMask {
            anchors.fill:parent
            source: source_figma_5_136
            maskSource: maskSource_figma_5_136
        }
        Image {
            id: source_figma_5_136
            layer.enabled: true
            fillMode: Image.PreserveAspectCrop
            visible: false
            mipmap: true
            anchors.fill:parent
            source: "images/9544714d8570945aa7fbeac2fd6c9962ce941501.jpg"
        }
        Shape {
            id: maskSource_figma_5_136
            anchors.fill: parent
            layer.enabled: true
            visible: false
            ShapePath {
                strokeColor: "transparent"
                strokeWidth:1
                fillColor:"black"
                fillRule: ShapePath.WindingFill
                PathSvg {
                    path: "M0 0L1136 0L1136 558L0 558L0 0Z"
                } 
            }
        }
        Shape {
            anchors.fill: parent
            ShapePath {
                strokeColor: "transparent"
                strokeWidth:1
                fillColor:"#00000000"
                id: svgpath_figma_5_136
                fillRule: ShapePath.WindingFill
                PathSvg {
                    path: "M0 0L1136 0L1136 558L0 558L0 0Z"
                } 
            }
        }
    } 
    Item {
        id: figma_28_543
        objectName:"png-transparent-logo-organization-graphy-brand-go-back-button-angle-text-trademark-removebg-preview 1"
        x:23
        y:32
        width:144
        height:168
        OpacityMask {
            anchors.fill:parent
            source: source_figma_28_543
            maskSource: maskSource_figma_28_543
        }
        Image {
            id: source_figma_28_543
            layer.enabled: true
            fillMode: Image.PreserveAspectCrop
            visible: false
            mipmap: true
            anchors.fill:parent
            source: "images/4d714cc963312ff6143d734db576159e7f45d0fc.png"
        }
        Shape {
            id: maskSource_figma_28_543
            anchors.fill: parent
            layer.enabled: true
            visible: false
            ShapePath {
                strokeColor: "transparent"
                strokeWidth:1
                fillColor:"black"
                fillRule: ShapePath.WindingFill
                PathSvg {
                    path: "M0 0L144 0L144 168L0 168L0 0Z"
                } 
            }
        }
        Shape {
            anchors.fill: parent
            ShapePath {
                strokeColor: "transparent"
                strokeWidth:1
                fillColor:"#00000000"
                id: svgpath_figma_28_543
                fillRule: ShapePath.WindingFill
                PathSvg {
                    path: "M0 0L144 0L144 168L0 168L0 0Z"
                } 
            }
        }
    } 
}
