//Generated by FigmaQML

import QtGraphicalEffects 1.14
import QtQuick 2.14
import QtQuick.Shapes 1.14
Rectangle {
    id: figma_5_32
    objectName:"Frame 2"
    x:-2041
    y:-728
    width:640
    height:686
    color:"#fff3c216"
    radius:30
    clip: true 
    Text {
        id: figma_5_33
        objectName:"Payment method"
        x:98
        y:36
        width:444
        height:33
        color:"#ff000000"
        wrapMode: TextEdit.WordWrap
        text:"Payment method"
        font.family: "MS Shell Dlg 2"
        font.italic: false
        font.letterSpacing: 0
        font.pixelSize: 50
        font.weight: Font.DemiBold
        horizontalAlignment: Text.AlignHCenter
        verticalAlignment: Text.AlignTop
    }
    Rectangle {
        id: figma_5_34
        objectName:"QR"
        x:20
        y:193
        width:594
        height:123
        color: "transparent"
        clip: false 
        Shape {
            id: figma_5_35
            objectName:"Rectangle 4"
            x:4
            y:3
            width:587
            height:120
            ShapePath {
                strokeColor: "transparent"
                strokeWidth:1
                fillColor:"#ff1e1e1e"
                id: svgpath_figma_5_35
                fillRule: ShapePath.WindingFill
                PathSvg {
                    path: "M0 30C0 13.4315 13.4315 0 30 0L557 0C573.569 0 587 13.4315 587 30L587 90C587 106.569 573.569 120 557 120L30 120C13.4315 120 0 106.569 0 90L0 30Z"
                } 
            }
        }
        Text {
            id: figma_5_36
            objectName:"QR Code"
            x: (figma_5_34.width - width) / 2 - 129.5
            y: (figma_5_34.height - height) / 2 + 4
            width:335
            height:47
            color:"#ffffffff"
            wrapMode: TextEdit.WordWrap
            text:"QR Code"
            font.family: "MS Shell Dlg 2"
            font.italic: false
            font.letterSpacing: 0
            font.pixelSize: 50
            font.weight: Font.DemiBold
            horizontalAlignment: Text.AlignHCenter
            verticalAlignment: Text.AlignTop
        }
        Rectangle {
            id: figma_5_37
            objectName:"qr-code-svgrepo-com 1"
            x:447
            y:0
            width:147
            height:123
            color: "transparent"
            clip: true 
            Item {
            anchors.fill:parent
            OpacityMask {
                anchors.fill:parent
                source: source_figma_5_38
                maskSource: mask_figma_5_38
            }

            Item {
                id: mask_figma_5_38
                anchors.fill:parent
                Rectangle {
                    id: figma_5_38
                    objectName:"path-1-inside-1"
                    x:33
                    y:27
                    width:36.75
                    height:30.75
                    color: "transparent"
                    clip: false 
                    Shape {
                        id: figma_5_39
                        objectName:"Vector"
                        x:0
                        y:0
                        width:36.75
                        height:30.75
                        ShapePath {
                            strokeColor: "transparent"
                            strokeWidth:1
                            fillColor:"#ffffffff"
                            id: svgpath_figma_5_39
                            fillRule: ShapePath.WindingFill
                            PathSvg {
                                path: "M33.075 0L3.675 0C1.64535 0 0 1.37672 0 3.075L0 27.675C0 29.3733 1.64535 30.75 3.675 30.75L33.075 30.75C35.1046 30.75 36.75 29.3733 36.75 27.675L36.75 3.075C36.75 1.37672 35.1046 0 33.075 0Z"
                            } 
                        }
                    }
                }
                visible:false
            }

            Item {
                id: source_figma_5_38
                anchors.fill:parent
                visible:false
            Item {
            anchors.fill:parent
            OpacityMask {
                anchors.fill:parent
                source: source_figma_5_41
                maskSource: mask_figma_5_41
            }

            Item {
                id: mask_figma_5_41
                anchors.fill:parent
                Rectangle {
                    id: figma_5_41
                    objectName:"path-2-inside-2"
                    x:77
                    y:27
                    width:36.75
                    height:30.75
                    color: "transparent"
                    clip: false 
                    Shape {
                        id: figma_5_42
                        objectName:"Vector"
                        x:0
                        y:0
                        width:36.75
                        height:30.75
                        ShapePath {
                            strokeColor: "transparent"
                            strokeWidth:1
                            fillColor:"#ffffffff"
                            id: svgpath_figma_5_42
                            fillRule: ShapePath.WindingFill
                            PathSvg {
                                path: "M33.075 0L3.675 0C1.64535 0 0 1.37672 0 3.075L0 27.675C0 29.3733 1.64535 30.75 3.675 30.75L33.075 30.75C35.1046 30.75 36.75 29.3733 36.75 27.675L36.75 3.075C36.75 1.37672 35.1046 0 33.075 0Z"
                            } 
                        }
                    }
                }
                visible:false
            }

            Item {
                id: source_figma_5_41
                anchors.fill:parent
                visible:false
            Item {
            anchors.fill:parent
            OpacityMask {
                anchors.fill:parent
                source: source_figma_5_44
                maskSource: mask_figma_5_44
            }

            Item {
                id: mask_figma_5_44
                anchors.fill:parent
                Rectangle {
                    id: figma_5_44
                    objectName:"path-3-inside-3"
                    x:33
                    y:64
                    width:36.75
                    height:30.75
                    color: "transparent"
                    clip: false 
                    Shape {
                        id: figma_5_45
                        objectName:"Vector"
                        x:0
                        y:0
                        width:36.75
                        height:30.75
                        ShapePath {
                            strokeColor: "transparent"
                            strokeWidth:1
                            fillColor:"#ffffffff"
                            id: svgpath_figma_5_45
                            fillRule: ShapePath.WindingFill
                            PathSvg {
                                path: "M33.075 0L3.675 0C1.64535 0 0 1.37672 0 3.075L0 27.675C0 29.3733 1.64535 30.75 3.675 30.75L33.075 30.75C35.1046 30.75 36.75 29.3733 36.75 27.675L36.75 3.075C36.75 1.37672 35.1046 0 33.075 0Z"
                            } 
                        }
                    }
                }
                visible:false
            }

            Item {
                id: source_figma_5_44
                anchors.fill:parent
                visible:false
            Item {
            anchors.fill:parent
            OpacityMask {
                anchors.fill:parent
                source: source_figma_5_47
                maskSource: mask_figma_5_47
            }

            Item {
                id: mask_figma_5_47
                anchors.fill:parent
                Rectangle {
                    id: figma_5_47
                    objectName:"path-4-inside-4"
                    x:77
                    y:64
                    width:36.75
                    height:30.75
                    color: "transparent"
                    clip: false 
                    Shape {
                        id: figma_5_48
                        objectName:"Vector"
                        x:0
                        y:0
                        width:36.75
                        height:30.75
                        ShapePath {
                            strokeColor: "transparent"
                            strokeWidth:1
                            fillColor:"#ffffffff"
                            id: svgpath_figma_5_48
                            fillRule: ShapePath.WindingFill
                            PathSvg {
                                path: "M33.075 0L3.675 0C1.64535 0 0 1.37672 0 3.075L0 27.675C0 29.3733 1.64535 30.75 3.675 30.75L33.075 30.75C35.1046 30.75 36.75 29.3733 36.75 27.675L36.75 3.075C36.75 1.37672 35.1046 0 33.075 0Z"
                            } 
                        }
                    }
                }
                visible:false
            }

            Item {
                id: source_figma_5_47
                anchors.fill:parent
                visible:false
                Shape {
                    id: figma_5_40
                    objectName:"Vector"
                    x:33
                    y:27
                    width:36.75
                    height:30.75
                    ShapePath {
                        joinStyle: ShapePath.MiterJoin
                        strokeColor: "#ffffffff"
                        strokeWidth:3
                        fillColor:"transparent"
                        id: svgpath_figma_5_40
                        fillRule: ShapePath.WindingFill
                        PathSvg {
                            path: "M3.675 1.5L33.075 1.5L33.075 -1.5L3.675 -1.5L3.675 1.5ZM33.075 1.5C34.5378 1.5 35.25 2.44447 35.25 3.075L38.25 3.075C38.25 0.308977 35.6715 -1.5 33.075 -1.5L33.075 1.5ZM35.25 3.075L35.25 27.675L38.25 27.675L38.25 3.075L35.25 3.075ZM35.25 27.675C35.25 28.3055 34.5378 29.25 33.075 29.25L33.075 32.25C35.6715 32.25 38.25 30.441 38.25 27.675L35.25 27.675ZM33.075 29.25L3.675 29.25L3.675 32.25L33.075 32.25L33.075 29.25ZM3.675 29.25C2.21224 29.25 1.5 28.3055 1.5 27.675L-1.5 27.675C-1.5 30.441 1.07846 32.25 3.675 32.25L3.675 29.25ZM1.5 27.675L1.5 3.075L-1.5 3.075L-1.5 27.675L1.5 27.675ZM1.5 3.075C1.5 2.44447 2.21224 1.5 3.675 1.5L3.675 -1.5C1.07846 -1.5 -1.5 0.308977 -1.5 3.075L1.5 3.075Z"
                        } 
                    }
                }
                Shape {
                    id: figma_5_43
                    objectName:"Vector"
                    x:77
                    y:27
                    width:36.75
                    height:30.75
                    ShapePath {
                        joinStyle: ShapePath.MiterJoin
                        strokeColor: "#ffffffff"
                        strokeWidth:3
                        fillColor:"transparent"
                        id: svgpath_figma_5_43
                        fillRule: ShapePath.WindingFill
                        PathSvg {
                            path: "M3.675 1.5L33.075 1.5L33.075 -1.5L3.675 -1.5L3.675 1.5ZM33.075 1.5C34.5378 1.5 35.25 2.44447 35.25 3.075L38.25 3.075C38.25 0.308977 35.6715 -1.5 33.075 -1.5L33.075 1.5ZM35.25 3.075L35.25 27.675L38.25 27.675L38.25 3.075L35.25 3.075ZM35.25 27.675C35.25 28.3055 34.5378 29.25 33.075 29.25L33.075 32.25C35.6715 32.25 38.25 30.441 38.25 27.675L35.25 27.675ZM33.075 29.25L3.675 29.25L3.675 32.25L33.075 32.25L33.075 29.25ZM3.675 29.25C2.21224 29.25 1.5 28.3055 1.5 27.675L-1.5 27.675C-1.5 30.441 1.07846 32.25 3.675 32.25L3.675 29.25ZM1.5 27.675L1.5 3.075L-1.5 3.075L-1.5 27.675L1.5 27.675ZM1.5 3.075C1.5 2.44447 2.21224 1.5 3.675 1.5L3.675 -1.5C1.07846 -1.5 -1.5 0.308977 -1.5 3.075L1.5 3.075Z"
                        } 
                    }
                }
                Shape {
                    id: figma_5_46
                    objectName:"Vector"
                    x:33
                    y:64
                    width:36.75
                    height:30.75
                    ShapePath {
                        joinStyle: ShapePath.MiterJoin
                        strokeColor: "#ffffffff"
                        strokeWidth:3
                        fillColor:"transparent"
                        id: svgpath_figma_5_46
                        fillRule: ShapePath.WindingFill
                        PathSvg {
                            path: "M3.675 1.5L33.075 1.5L33.075 -1.5L3.675 -1.5L3.675 1.5ZM33.075 1.5C34.5378 1.5 35.25 2.44447 35.25 3.075L38.25 3.075C38.25 0.308977 35.6715 -1.5 33.075 -1.5L33.075 1.5ZM35.25 3.075L35.25 27.675L38.25 27.675L38.25 3.075L35.25 3.075ZM35.25 27.675C35.25 28.3055 34.5378 29.25 33.075 29.25L33.075 32.25C35.6715 32.25 38.25 30.441 38.25 27.675L35.25 27.675ZM33.075 29.25L3.675 29.25L3.675 32.25L33.075 32.25L33.075 29.25ZM3.675 29.25C2.21224 29.25 1.5 28.3055 1.5 27.675L-1.5 27.675C-1.5 30.441 1.07846 32.25 3.675 32.25L3.675 29.25ZM1.5 27.675L1.5 3.075L-1.5 3.075L-1.5 27.675L1.5 27.675ZM1.5 3.075C1.5 2.44447 2.21224 1.5 3.675 1.5L3.675 -1.5C1.07846 -1.5 -1.5 0.308977 -1.5 3.075L1.5 3.075Z"
                        } 
                    }
                }
                Shape {
                    id: figma_5_49
                    objectName:"Vector"
                    x:77
                    y:64
                    width:36.75
                    height:30.75
                    ShapePath {
                        joinStyle: ShapePath.MiterJoin
                        strokeColor: "#ffffffff"
                        strokeWidth:3
                        fillColor:"#ffffffff"
                        id: svgpath_figma_5_49
                        fillRule: ShapePath.WindingFill
                        PathSvg {
                            path: "M33.075 0L3.675 0C1.64535 0 0 1.37672 0 3.075L0 27.675C0 29.3733 1.64535 30.75 3.675 30.75L33.075 30.75C35.1046 30.75 36.75 29.3733 36.75 27.675L36.75 3.075C36.75 1.37672 35.1046 0 33.075 0Z"
                        } 
                    }
                }
                Shape {
                    id: figma_5_50
                    objectName:"Vector"
                    x:22
                    y:18
                    width:25.725
                    height:0
                    ShapePath {
                        joinStyle: ShapePath.MiterJoin
                        strokeColor: "#ffffffff"
                        strokeWidth:2
                        fillColor:"transparent"
                        id: svgpath_figma_5_50
                        fillRule: ShapePath.WindingFill
                        PathSvg {
                            path: "M0 -1C-0.552285 -1 -1 -0.552285 -1 0C-1 0.552285 -0.552285 1 0 1L0 -1ZM25.725 1C26.2773 1 26.725 0.552285 26.725 0C26.725 -0.552285 26.2773 -1 25.725 -1L25.725 1ZM0 1L25.725 1L25.725 -1L0 -1L0 1Z"
                        } 
                    }
                }
                Shape {
                    id: figma_5_51
                    objectName:"Vector"
                    x:22
                    y:18
                    width:0
                    height:21.525
                    ShapePath {
                        joinStyle: ShapePath.MiterJoin
                        strokeColor: "#ffffffff"
                        strokeWidth:2
                        fillColor:"transparent"
                        id: svgpath_figma_5_51
                        fillRule: ShapePath.WindingFill
                        PathSvg {
                            path: "M1 0C1 -0.552285 0.552285 -1 0 -1C-0.552285 -1 -1 -0.552285 -1 0L1 0ZM-1 21.525C-1 22.0773 -0.552285 22.525 0 22.525C0.552285 22.525 1 22.0773 1 21.525L-1 21.525ZM-1 0L-1 21.525L1 21.525L1 0L-1 0Z"
                        } 
                    }
                }
                Shape {
                    id: figma_5_52
                    objectName:"Vector"
                    x:22
                    y:83
                    width:0
                    height:21.525
                    ShapePath {
                        joinStyle: ShapePath.MiterJoin
                        strokeColor: "#ffffffff"
                        strokeWidth:2
                        fillColor:"transparent"
                        id: svgpath_figma_5_52
                        fillRule: ShapePath.WindingFill
                        PathSvg {
                            path: "M-1 21.525C-1 22.0773 -0.552285 22.525 0 22.525C0.552285 22.525 1 22.0773 1 21.525L-1 21.525ZM1 0C1 -0.552285 0.552285 -1 0 -1C-0.552285 -1 -1 -0.552285 -1 0L1 0ZM1 21.525L1 0L-1 0L-1 21.525L1 21.525Z"
                        } 
                    }
                }
                Shape {
                    id: figma_5_53
                    objectName:"Vector"
                    x:22
                    y:104
                    width:25.725
                    height:0
                    ShapePath {
                        joinStyle: ShapePath.MiterJoin
                        strokeColor: "#ffffffff"
                        strokeWidth:2
                        fillColor:"transparent"
                        id: svgpath_figma_5_53
                        fillRule: ShapePath.WindingFill
                        PathSvg {
                            path: "M0 -1C-0.552285 -1 -1 -0.552285 -1 0C-1 0.552285 -0.552285 1 0 1L0 -1ZM25.725 1C26.2773 1 26.725 0.552285 26.725 0C26.725 -0.552285 26.2773 -1 25.725 -1L25.725 1ZM0 1L25.725 1L25.725 -1L0 -1L0 1Z"
                        } 
                    }
                }
                Shape {
                    id: figma_5_54
                    objectName:"Vector"
                    x:99
                    y:104
                    width:25.725
                    height:0
                    ShapePath {
                        joinStyle: ShapePath.MiterJoin
                        strokeColor: "#ffffffff"
                        strokeWidth:2
                        fillColor:"transparent"
                        id: svgpath_figma_5_54
                        fillRule: ShapePath.WindingFill
                        PathSvg {
                            path: "M25.725 1C26.2773 1 26.725 0.552285 26.725 0C26.725 -0.552285 26.2773 -1 25.725 -1L25.725 1ZM0 -1C-0.552285 -1 -1 -0.552285 -1 0C-1 0.552285 -0.552285 1 0 1L0 -1ZM25.725 -1L0 -1L0 1L25.725 1L25.725 -1Z"
                        } 
                    }
                }
                Shape {
                    id: figma_5_55
                    objectName:"Vector"
                    x:124
                    y:83
                    width:0
                    height:21.525
                    ShapePath {
                        joinStyle: ShapePath.MiterJoin
                        strokeColor: "#ffffffff"
                        strokeWidth:2
                        fillColor:"transparent"
                        id: svgpath_figma_5_55
                        fillRule: ShapePath.WindingFill
                        PathSvg {
                            path: "M-1 21.525C-1 22.0773 -0.552285 22.525 0 22.525C0.552285 22.525 1 22.0773 1 21.525L-1 21.525ZM1 0C1 -0.552285 0.552285 -1 0 -1C-0.552285 -1 -1 -0.552285 -1 0L1 0ZM1 21.525L1 0L-1 0L-1 21.525L1 21.525Z"
                        } 
                    }
                }
                Shape {
                    id: figma_5_56
                    objectName:"Vector"
                    x:124
                    y:18
                    width:0
                    height:21.525
                    ShapePath {
                        joinStyle: ShapePath.MiterJoin
                        strokeColor: "#ffffffff"
                        strokeWidth:2
                        fillColor:"transparent"
                        id: svgpath_figma_5_56
                        fillRule: ShapePath.WindingFill
                        PathSvg {
                            path: "M1 0C1 -0.552285 0.552285 -1 0 -1C-0.552285 -1 -1 -0.552285 -1 0L1 0ZM-1 21.525C-1 22.0773 -0.552285 22.525 0 22.525C0.552285 22.525 1 22.0773 1 21.525L-1 21.525ZM-1 0L-1 21.525L1 21.525L1 0L-1 0Z"
                        } 
                    }
                }
                Shape {
                    id: figma_5_57
                    objectName:"Vector"
                    x:99
                    y:18
                    width:25.725
                    height:0
                    ShapePath {
                        joinStyle: ShapePath.MiterJoin
                        strokeColor: "#ffffffff"
                        strokeWidth:2
                        fillColor:"transparent"
                        id: svgpath_figma_5_57
                        fillRule: ShapePath.WindingFill
                        PathSvg {
                            path: "M25.725 1C26.2773 1 26.725 0.552285 26.725 0C26.725 -0.552285 26.2773 -1 25.725 -1L25.725 1ZM0 -1C-0.552285 -1 -1 -0.552285 -1 0C-1 0.552285 -0.552285 1 0 1L0 -1ZM25.725 -1L0 -1L0 1L25.725 1L25.725 -1Z"
                        } 
                    }
                }
                }
            }
        }
    }
    Rectangle {
        id: figma_5_58
        objectName:"Bar"
        x:24
        y:366
        width:593
        height:120
        color: "transparent"
        clip: false 
        Shape {
            id: figma_5_59
            objectName:"Rectangle 4"
            x: (figma_5_58.width - width) / 2
            y: (figma_5_58.height - height) / 2
            width:593
            height:120
            ShapePath {
                strokeColor: "transparent"
                strokeWidth:1
                fillColor:"#ff1e1e1e"
                id: svgpath_figma_5_59
                fillRule: ShapePath.WindingFill
                PathSvg {
                    path: "M0 30C0 13.4315 13.4315 0 30 0L563 0C579.569 0 593 13.4315 593 30L593 90C593 106.569 579.569 120 563 120L30 120C13.4315 120 0 106.569 0 90L0 30Z"
                } 
            }
        }
        Text {
            id: figma_5_60
            objectName:"Bar Code"
            x: (figma_5_58.width - width) / 2 - 122
            y: (figma_5_58.height - height) / 2 + 12.5
            width:249
            height:67
            color:"#ffffffff"
            wrapMode: TextEdit.WordWrap
            text:"Bar Code"
            font.family: "MS Shell Dlg 2"
            font.italic: false
            font.letterSpacing: 0
            font.pixelSize: 50
            font.weight: Font.DemiBold
            horizontalAlignment: Text.AlignLeft
            verticalAlignment: Text.AlignTop
        }
        Rectangle {
            id: figma_5_61
            objectName:"bar-code-svgrepo-com 1"
            x:469
            y:10
            width:112
            height:100
            color: "transparent"
            clip: true 
            Rectangle {
                id: figma_5_62
                objectName:"Group"
                x:0
                y:16
                width:129.912
                height:66.6667
                color: "transparent"
                clip: false 
                Shape {
                    id: figma_5_63
                    objectName:"Vector"
                    x:0
                    y:0
                    width:12.4444
                    height:66.6667
                    ShapePath {
                        strokeColor: "transparent"
                        strokeWidth:1
                        fillColor:"#ffffffff"
                        id: svgpath_figma_5_63
                        fillRule: ShapePath.WindingFill
                        PathSvg {
                            path: "M12.4444 0L0 0L0 66.6667L12.4444 66.6667L12.4444 0Z"
                        } 
                    }
                }
                Shape {
                    id: figma_5_64
                    objectName:"Vector"
                    x:37
                    y:0
                    width:12.4444
                    height:66.6667
                    ShapePath {
                        strokeColor: "transparent"
                        strokeWidth:1
                        fillColor:"#ffffffff"
                        id: svgpath_figma_5_64
                        fillRule: ShapePath.WindingFill
                        PathSvg {
                            path: "M12.4444 0L0 0L0 66.6667L12.4444 66.6667L12.4444 0Z"
                        } 
                    }
                }
                Shape {
                    id: figma_5_65
                    objectName:"Vector"
                    x:58
                    y:0
                    width:12.4444
                    height:66.6667
                    ShapePath {
                        strokeColor: "transparent"
                        strokeWidth:1
                        fillColor:"#ffffffff"
                        id: svgpath_figma_5_65
                        fillRule: ShapePath.WindingFill
                        PathSvg {
                            path: "M12.4444 0L0 0L0 66.6667L12.4444 66.6667L12.4444 0Z"
                        } 
                    }
                }
                Shape {
                    id: figma_5_66
                    objectName:"Vector"
                    x:111
                    y:0
                    width:18.4781
                    height:66.6667
                    ShapePath {
                        strokeColor: "transparent"
                        strokeWidth:1
                        fillColor:"#ffffffff"
                        id: svgpath_figma_5_66
                        fillRule: ShapePath.WindingFill
                        PathSvg {
                            path: "M18.4781 0L0 0L0 66.6667L18.4781 66.6667L18.4781 0Z"
                        } 
                    }
                }
                Shape {
                    id: figma_5_67
                    objectName:"Vector"
                    x:21
                    y:0
                    width:6.03367
                    height:66.6667
                    ShapePath {
                        strokeColor: "transparent"
                        strokeWidth:1
                        fillColor:"#ffffffff"
                        id: svgpath_figma_5_67
                        fillRule: ShapePath.WindingFill
                        PathSvg {
                            path: "M6.03367 0L0 0L0 66.6667L6.03367 66.6667L6.03367 0Z"
                        } 
                    }
                }
                Shape {
                    id: figma_5_68
                    objectName:"Vector"
                    x:80
                    y:0
                    width:6.03367
                    height:66.6667
                    ShapePath {
                        strokeColor: "transparent"
                        strokeWidth:1
                        fillColor:"#ffffffff"
                        id: svgpath_figma_5_68
                        fillRule: ShapePath.WindingFill
                        PathSvg {
                            path: "M6.03367 0L0 0L0 66.6667L6.03367 66.6667L6.03367 0Z"
                        } 
                    }
                }
                Shape {
                    id: figma_5_69
                    objectName:"Vector"
                    x:96
                    y:0
                    width:6.03367
                    height:66.6667
                    ShapePath {
                        strokeColor: "transparent"
                        strokeWidth:1
                        fillColor:"#ffffffff"
                        id: svgpath_figma_5_69
                        fillRule: ShapePath.WindingFill
                        PathSvg {
                            path: "M6.03367 0L0 0L0 66.6667L6.03367 66.6667L6.03367 0Z"
                        } 
                    }
                }
            }
        }
    }
    Rectangle {
        id: figma_5_73
        objectName:"RFid"
        x:20
        y:536
        width:593
        height:120
        color: "transparent"
        clip: false 
        Shape {
            id: figma_5_74
            objectName:"Rectangle 4"
            x: (figma_5_73.width - width) / 2
            y: (figma_5_73.height - height) / 2
            width:593
            height:120
            ShapePath {
                strokeColor: "transparent"
                strokeWidth:1
                fillColor:"#ff1e1e1e"
                id: svgpath_figma_5_74
                fillRule: ShapePath.WindingFill
                PathSvg {
                    path: "M0 30C0 13.4315 13.4315 0 30 0L563 0C579.569 0 593 13.4315 593 30L593 90C593 106.569 579.569 120 563 120L30 120C13.4315 120 0 106.569 0 90L0 30Z"
                } 
            }
        }
        Text {
            id: figma_5_75
            objectName:"RFID"
            x: (figma_5_73.width - width) / 2 - 186.5
            y: (figma_5_73.height - height) / 2
            width:138
            height:60
            color:"#ffffffff"
            wrapMode: TextEdit.WordWrap
            text:" RFID
"
            font.family: "MS Shell Dlg 2"
            font.italic: false
            font.letterSpacing: 0
            font.pixelSize: 50
            font.weight: Font.DemiBold
            horizontalAlignment: Text.AlignLeft
            verticalAlignment: Text.AlignTop
        }
        Rectangle {
            id: figma_5_76
            objectName:"nfc-svgrepo-com 1"
            x:500
            y:19
            width:81
            height:71.4194
            color: "transparent"
            clip: true 
            Rectangle {
                id: figma_5_77
                objectName:"XMLID_2_"
                x:0
                y:0
                width:81
                height:71.4194
                color: "transparent"
                clip: false 
                Shape {
                    id: figma_5_78
                    objectName:"XMLID_4_"
                    x:0
                    y:0
                    width:81
                    height:71.4194
                    ShapePath {
                        strokeColor: "transparent"
                        strokeWidth:0.870968
                        fillColor:"#ffffffff"
                        id: svgpath_figma_5_78
                        fillRule: ShapePath.WindingFill
                        PathSvg {
                            path: "M77.3182 0L3.68182 0C1.64847 0 0 1.45349 0 3.24633L0 68.173C0 69.9659 1.64847 71.4194 3.68182 71.4194L77.3182 71.4194C79.3515 71.4194 81 69.9659 81 68.173L81 3.24633C81 1.45349 79.3515 0 77.3182 0ZM73.6364 64.9267L7.36364 64.9267L7.36364 6.49267L73.6364 6.49267L73.6364 64.9267Z"
                        } 
                    }
                }
                Shape {
                    id: figma_5_79
                    objectName:"XMLID_7_"
                    x:14
                    y:12
                    width:51.5455
                    height:45.4487
                    ShapePath {
                        strokeColor: "transparent"
                        strokeWidth:0.870968
                        fillColor:"#ffffffff"
                        id: svgpath_figma_5_79
                        fillRule: ShapePath.WindingFill
                        PathSvg {
                            path: "M3.68182 45.4487L47.8636 45.4487C49.897 45.4487 51.5455 43.9952 51.5455 42.2023L51.5455 3.24633C51.5455 1.45349 49.897 0 47.8636 0L25.7727 0C23.7394 0 22.0909 1.45349 22.0909 3.24633L22.0909 13.5437C17.8055 14.8838 14.7273 18.4922 14.7273 22.7243C14.7273 28.0944 19.682 32.4633 25.7727 32.4633C31.8634 32.4633 36.8182 28.0944 36.8182 22.7243C36.8182 18.4922 33.7399 14.884 29.4545 13.5437L29.4545 6.49267L44.1818 6.49267L44.1818 38.956L7.36364 38.956L7.36364 6.49267L8.59091 6.49267C10.6243 6.49267 12.2727 5.03918 12.2727 3.24633C12.2727 1.45349 10.6243 0 8.59091 0L3.68182 0C1.64847 0 0 1.45349 0 3.24633L0 42.2023C0 43.9952 1.64847 45.4487 3.68182 45.4487ZM25.7727 25.9707C23.7426 25.9707 22.0909 24.5144 22.0909 22.7243C22.0909 20.9343 23.7426 19.478 25.7727 19.478C27.8029 19.478 29.4545 20.9343 29.4545 22.7243C29.4545 24.5144 27.8029 25.9707 25.7727 25.9707Z"
                        } 
                    }
                }
            }
        }
    }
}
