//Generated by FigmaQML

import QtGraphicalEffects 1.14
import QtQuick 2.14
import QtQuick.Shapes 1.14
Rectangle {
    id: figma_5_138
    objectName:"Slide 16:9 - 4"
    x:-191
    y:370
    width:1920
    height:1080
    color: "transparent"
    clip: true 
    Shape {
        id: figma_5_139
        objectName:"wallpaperbetter 3"
        x:0
        y:0
        width:1920
        height:1200
        ShapePath {
            strokeColor: "transparent"
            strokeWidth:1.01204
            fillColor:"#ffffffff"
            id: svgpath_figma_5_139
            fillRule: ShapePath.WindingFill
            PathSvg {
                path: "M0 0L1920 0L1920 1200L0 1200L0 0Z"
            } 
        }
    }
    Item {
        id: figma_5_140
        objectName:"BG-8 1"
        x:0
        y:-25
        width:1920
        height:1130
        OpacityMask {
            anchors.fill:parent
            source: source_figma_5_140
            maskSource: maskSource_figma_5_140
        }
        Image {
            id: source_figma_5_140
            layer.enabled: true
            fillMode: Image.PreserveAspectCrop
            visible: false
            mipmap: true
            anchors.fill:parent
            source: "images/c75db96fe239f472297f43674c2bc4f0b17747a5.jpg"
        }
        Shape {
            id: maskSource_figma_5_140
            anchors.fill: parent
            layer.enabled: true
            visible: false
            ShapePath {
                strokeColor: "transparent"
                strokeWidth:1
                fillColor:"black"
                fillRule: ShapePath.WindingFill
                PathSvg {
                    path: "M0 0L1920 0L1920 1130L0 1130L0 0Z"
                } 
            }
        }
        Shape {
            anchors.fill: parent
            ShapePath {
                strokeColor: "transparent"
                strokeWidth:1
                fillColor:"#00000000"
                id: svgpath_figma_5_140
                fillRule: ShapePath.WindingFill
                PathSvg {
                    path: "M0 0L1920 0L1920 1130L0 1130L0 0Z"
                } 
            }
        }
    } 
    Text {
        id: figma_5_141
        objectName:"06:15 PM Friday, July 22nd"
        x:1402
        y:28
        width:446.308
        height:107.276
        color:"#ff000000"
        wrapMode: TextEdit.WordWrap
        text:"06:15 PM
Friday, July 22nd"
        font.family: "MS Shell Dlg 2"
        font.italic: false
        font.letterSpacing: 0
        font.pixelSize: 24
        font.weight: Font.Normal
        horizontalAlignment: Text.AlignRight
        verticalAlignment: Text.AlignTop
    }
    Item {
        id: figma_5_142
        objectName:"MicrosoftTeams-image (3) 1"
        x:23
        y:982
        width:1874
        height:76
        OpacityMask {
            anchors.fill:parent
            source: source_figma_5_142
            maskSource: maskSource_figma_5_142
        }
        Image {
            id: source_figma_5_142
            layer.enabled: true
            fillMode: Image.PreserveAspectCrop
            visible: false
            mipmap: true
            anchors.fill:parent
            source: "images/edf016518fee329caa534e7f7800bf2d6d8caa14.png"
        }
        Shape {
            id: maskSource_figma_5_142
            anchors.fill: parent
            layer.enabled: true
            visible: false
            ShapePath {
                strokeColor: "transparent"
                strokeWidth:1
                fillColor:"black"
                fillRule: ShapePath.WindingFill
                PathSvg {
                    path: "M0 0L1874 0L1874 76L0 76L0 0Z"
                } 
            }
        }
        Shape {
            anchors.fill: parent
            ShapePath {
                strokeColor: "transparent"
                strokeWidth:1
                fillColor:"#00000000"
                id: svgpath_figma_5_142
                fillRule: ShapePath.WindingFill
                PathSvg {
                    path: "M0 0L1874 0L1874 76L0 76L0 0Z"
                } 
            }
        }
    } 
    Text {
        id: figma_5_143
        objectName:"Please touch your ID card to the RFID reader"
        x:250
        y:189
        width:1419
        height:85
        color:"#ff000000"
        wrapMode: TextEdit.WordWrap
        text:"Please touch your ID card to the RFID reader"
        font.family: "MS Shell Dlg 2"
        font.italic: false
        font.letterSpacing: 0
        font.pixelSize: 64
        font.weight: Font.Normal
        horizontalAlignment: Text.AlignRight
        verticalAlignment: Text.AlignTop
    }
    Item {
        id: figma_5_146
        objectName:"istockphoto-1200536941-612x612 1"
        x:479
        y:344
        width:962
        height:612
        OpacityMask {
            anchors.fill:parent
            source: source_figma_5_146
            maskSource: maskSource_figma_5_146
        }
        Image {
            id: source_figma_5_146
            layer.enabled: true
            fillMode: Image.PreserveAspectCrop
            visible: false
            mipmap: true
            anchors.fill:parent
            source: "images/a7fab55b864eaa30694178259b8ac07f5584d5d2.jpg"
        }
        Shape {
            id: maskSource_figma_5_146
            anchors.fill: parent
            layer.enabled: true
            visible: false
            ShapePath {
                strokeColor: "transparent"
                strokeWidth:1
                fillColor:"black"
                fillRule: ShapePath.WindingFill
                PathSvg {
                    path: "M0 0L962 0L962 612L0 612L0 0Z"
                } 
            }
        }
        Shape {
            anchors.fill: parent
            ShapePath {
                strokeColor: "transparent"
                strokeWidth:1
                fillColor:"#00000000"
                id: svgpath_figma_5_146
                fillRule: ShapePath.WindingFill
                PathSvg {
                    path: "M0 0L962 0L962 612L0 612L0 0Z"
                } 
            }
        }
    } 
    Item {
        id: figma_28_544
        objectName:"png-transparent-logo-organization-graphy-brand-go-back-button-angle-text-trademark-removebg-preview 2"
        x:23
        y:64
        width:144
        height:168
        OpacityMask {
            anchors.fill:parent
            source: source_figma_28_544
            maskSource: maskSource_figma_28_544
        }
        Image {
            id: source_figma_28_544
            layer.enabled: true
            fillMode: Image.PreserveAspectCrop
            visible: false
            mipmap: true
            anchors.fill:parent
            source: "images/4d714cc963312ff6143d734db576159e7f45d0fc.png"
        }
        Shape {
            id: maskSource_figma_28_544
            anchors.fill: parent
            layer.enabled: true
            visible: false
            ShapePath {
                strokeColor: "transparent"
                strokeWidth:1
                fillColor:"black"
                fillRule: ShapePath.WindingFill
                PathSvg {
                    path: "M0 0L144 0L144 168L0 168L0 0Z"
                } 
            }
        }
        Shape {
            anchors.fill: parent
            ShapePath {
                strokeColor: "transparent"
                strokeWidth:1
                fillColor:"#00000000"
                id: svgpath_figma_28_544
                fillRule: ShapePath.WindingFill
                PathSvg {
                    path: "M0 0L144 0L144 168L0 168L0 0Z"
                } 
            }
        }
    } 
}
